### PR TITLE
added code for HelloWorld in jetpack Compose #44

### PR DESCRIPTION
**Pull request by RockingRishav**
Screenshot_20221001-100538_Helloworld

### CODE REVIEW

**Comment by RockingRishav** [comment]
Please review this PR and suggest changes if required otherwise merge it with label Hacktoberfest-Accepted.

**Review by SaicharanKandukuri — CHANGES_REQUESTED** [review]
@RockingRishav Can you also add add gradlew script files
like the 
`gradlew.bat`
`gradlew`
gradle properties file

**Comment by RockingRishav** [comment]
Added it can you please review again?

**Review by SaicharanKandukuri — APPROVED** [review]
Things looks good

> This PR will be merged after Hactober fest started
Hfest-Badge-2-Color-Manga

**Comment by RockingRishav** [comment]
Thank You, I am a newbie to open source,feeling happy on Contribution can you please Merge it with Hacktoberfest-accepted label.

**Comment by SaicharanKandukuri** [comment]
> Thank You, I am a newbie to open source,feeling happy on Contribution can you please Merge it with Hacktoberfest-accepted label.

@RockingRishav sure!

> and welcome to OpenSource make sure explore GitHub

**Pull request merged**
